version: '3'
services:
  app:
    container_name: 'restaurants'
    restart: always
    build: .
    ports:
      - '80:5000'
    links:
      - mongo
  mongo:
    container_name: 'mongodb'
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Alumne1234*
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 81:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Alumne1234*